### ISSUE TITLE
Calculate icon is not active ?

### ISSUE THREAD

**Issue by haseeb17** [HenrikSpa/GroupStats#4]
Hi all i am having an issue using group stats my layers are loaded on the right control panel but the data is not shown on the left pane and by after dragging the values to the lower right pane the calculate icon is not active that's why i am unable to load whats the problem please help?

![Annotation 2020-04-12 034748](https://user-images.githubusercontent.com/32012032/79056485-82270c80-7c70-11ea-8196-d322a18e6f5d.jpg)

**Comment by kikislater** [comment]
It's not an issue, 'area' should be on last right below box ...
https://anitagraser.com/2013/02/02/group-stats-tutorial/
